# This config file for Travis CI
sudo: required

language: generic

services:
  - docker

git:
  quiet: true
  submodules: true

notifications:
  email:
    on_success: never
    on_failure: never

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - UPSTREAM_WORKSPACE=.rosinstall
    - ROS_REPO=ros
    - CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug"

jobs:
  include:
    - os: linux
      dist: bionic
      language: cpp
      env:
      - DOCKER_IMAGE=mpowelson/bionic-qt-ros:eloquent
      - ROS_DISTRO="eloquent"
      - NOT_TEST_BUILD=true
      - ADDITIONAL_DEBS="libompl-dev"
      - BEFORE_INIT="apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654"
      - BADGE=eloquent
      cache:
        directories:
          - $HOME/.ccache

install:
  - git clone --quiet --depth 1 https://github.com/ipa-mdl/industrial_ci.git .industrial_ci -b revert-revert-colcon-chain

script:
  - .industrial_ci/travis.sh

